package ru.imagnifi.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ru.imagnifi.model.District;

import ru.imagnifi.service.DistrictLocalServiceUtil;

/**
 * The extended model base implementation for the District service. Represents a row in the &quot;district_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DistrictImpl}.
 * </p>
 *
 * @author imagnifi
 * @see DistrictImpl
 * @see ru.imagnifi.model.District
 * @generated
 */
public abstract class DistrictBaseImpl extends DistrictModelImpl
    implements District {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a district model instance should use the {@link District} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DistrictLocalServiceUtil.addDistrict(this);
        } else {
            DistrictLocalServiceUtil.updateDistrict(this);
        }
    }
}
