package ru.imagnifi.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the District service. Represents a row in the &quot;district_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.imagnifi.model.impl.DistrictModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.imagnifi.model.impl.DistrictImpl}.
 * </p>
 *
 * @author imagnifi
 * @see District
 * @see ru.imagnifi.model.impl.DistrictImpl
 * @see ru.imagnifi.model.impl.DistrictModelImpl
 * @generated
 */
public interface DistrictModel extends BaseModel<District> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a district model instance should use the {@link District} interface instead.
     */

    /**
     * Returns the primary key of this district.
     *
     * @return the primary key of this district
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this district.
     *
     * @param primaryKey the primary key of this district
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this district.
     *
     * @return the uuid of this district
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this district.
     *
     * @param uuid the uuid of this district
     */
    public void setUuid(String uuid);

    /**
     * Returns the district ID of this district.
     *
     * @return the district ID of this district
     */
    public long getDistrictId();

    /**
     * Sets the district ID of this district.
     *
     * @param districtId the district ID of this district
     */
    public void setDistrictId(long districtId);

    /**
     * Returns the name of this district.
     *
     * @return the name of this district
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this district.
     *
     * @param name the name of this district
     */
    public void setName(String name);

    /**
     * Returns the number of this district.
     *
     * @return the number of this district
     */
    public int getNumber();

    /**
     * Sets the number of this district.
     *
     * @param number the number of this district
     */
    public void setNumber(int number);

    /**
     * Returns the status of this district.
     *
     * @return the status of this district
     */
    public boolean getStatus();

    /**
     * Returns <code>true</code> if this district is status.
     *
     * @return <code>true</code> if this district is status; <code>false</code> otherwise
     */
    public boolean isStatus();

    /**
     * Sets whether this district is status.
     *
     * @param status the status of this district
     */
    public void setStatus(boolean status);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.imagnifi.model.District district);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.imagnifi.model.District> toCacheModel();

    @Override
    public ru.imagnifi.model.District toEscapedModel();

    @Override
    public ru.imagnifi.model.District toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
